"""ATT&CK coverage reporting for the rule pack.

Produces a Markdown table for humans and an ATT&CK Navigator layer for the
Navigator UI, so "what do we actually detect?" has a concrete answer that is
regenerated from the rules themselves rather than maintained by hand.
"""

from __future__ import annotations

import json
from pathlib import Path

from .rule import Rule

# Technique names for the techniques this pack covers. Kept local and explicit
# so the tool needs no network access in CI.
TECHNIQUE_NAMES = {
    "T1059.001": "Command and Scripting Interpreter: PowerShell",
    "T1078.004": "Valid Accounts: Cloud Accounts",
    "T1098.003": "Account Manipulation: Additional Cloud Roles",
    "T1110": "Brute Force",
    "T1490": "Inhibit System Recovery",
    "T1543.003": "Create or Modify System Process: Windows Service",
    "T1562.001": "Impair Defenses: Disable or Modify Tools",
    "T1562.008": "Impair Defenses: Disable or Modify Cloud Logs",
    "T1571": "Non-Standard Port",
}


def technique_index(rules: list[Rule]) -> dict[str, list[Rule]]:
    index: dict[str, list[Rule]] = {}
    for rule in rules:
        for technique in rule.techniques:
            index.setdefault(technique, []).append(rule)
    return dict(sorted(index.items()))


def markdown_table(rules: list[Rule]) -> str:
    index = technique_index(rules)
    lines = [
        "| ATT&CK technique | Name | Data source | Rules |",
        "|---|---|---|---|",
    ]
    for technique, covering in index.items():
        products = sorted({r.product for r in covering if r.product})
        titles = "<br>".join(r.title for r in covering)
        lines.append(
            f"| {technique} | {TECHNIQUE_NAMES.get(technique, 'see ATT&CK')} "
            f"| {', '.join(products) or 'n/a'} | {titles} |"
        )
    lines.append("")
    lines.append(f"{len(index)} techniques covered by {len(rules)} rules.")
    return "\n".join(lines)


def navigator_layer(rules: list[Rule], name: str = "HuntForge") -> dict:
    index = technique_index(rules)
    return {
        "name": name,
        "versions": {"attack": "14", "navigator": "4.9.0", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": "Techniques covered by the rules in this repository.",
        "techniques": [
            {
                "techniqueID": technique,
                "score": len(covering),
                "comment": "; ".join(r.title for r in covering),
                "enabled": True,
            }
            for technique, covering in index.items()
        ],
        "gradient": {"colors": ["#ffffff", "#ff6666"], "minValue": 0, "maxValue": 3},
    }


def write_reports(rules: list[Rule], markdown_path: Path, layer_path: Path) -> None:
    header = (
        "# ATT&CK coverage\n\n"
        "Generated by `python -m huntforge coverage`. Do not edit by hand.\n\n"
    )
    markdown_path.write_text(header + markdown_table(rules) + "\n", encoding="utf-8")
    layer_path.write_text(json.dumps(navigator_layer(rules), indent=2) + "\n", encoding="utf-8")
